# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'git@github.com:RevelSystems/CocoaPodsSpecs.git'

target 'AuthKitCocoapod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuthKitCocoapod
  
  pod 'Auth0', '2.0.0'
  pod 'SimpleKeychain', '0.12.5'
  pod 'JWTDecode', '2.6.3'

  target 'AuthKitCocoapodTests' do
    # Pods for testing
  end

end
